name: apply
on:
  push:
    branches:
      - develop

jobs:
  tfapply:
    name: merge
    runs-on: ubuntu-latest
    steps:
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
