name: terraform
on:
  workflow_call:
    inputs:
      terraform_directory:
        type: string
        required: true
        description: 'Terraform folder'
      path:
        type: string
        required: true
        description: 'Path for the tfstate in S3'
    secrets:
      aws-access-key-id:
        required: true
        description: 'AWS Access Id'
      aws-secret-access-key:
        required: true
        description: 'AWS Secret Key'
      aws-region:
        required: true
        description: 'AWS Region to be used'
      aws-s3-bucket:
        required: true
        description: 'AWS S3 Bucket'

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    env:
      aws-s3-bucket: ${{ secrets.aws-s3-bucket }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        id: setup-tf
        uses: hashicorp/setup-terraform@v2

      - name: Setup AWS Credentials
        id: setup-aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ secrets.aws-region }}

      - name: Terraform init
        id: init
        working-directory: ${{ inputs.terraform_directory }}
        run: terraform init -backend-config="path=${{ inputs.path }}"

      - name: Terraform format
        id: fmt
        run: terraform fmt -recursive

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        working-directory: ${{ inputs.terraform_directory }}
        run: terraform plan

      - name: Terraform apply
        id: apply
        working-directory: ${{ inputs.terraform_directory }}
        run: terraform apply -auto-approve